function rl_choose_your_reliability_threshold()
addpath('/data/Siegle/matlab/afni_matlab');

 ROIs={'binminicolin_Amygdala_MNIspace_epan+orig.BRIK',...
       'binminicolin_DLPFC_epan+orig.BRIK',...
       'binminicolin_rACC_epan+orig.BRIK',...
       'sgACC_mask+orig.BRIK',...
       'sg_ACC_liberally_thresholded+orig.BRIK'};

ICCs_maps={'icc_canonical_amplitude_all_sample_computed_with_matlab+orig.BRIK',...
           'icc_canonical_amplitude_patients_computed_with_matlab+orig.BRIK',...
           'icc_amplitude_all_sample_computed_with_matlab+orig.BRIK',...
           'icc_amplitude_patients_computed_with_matlab+orig.BRIK',...
           'icc_area_under_the_curve_all_sample_computed_with_matlab+orig.BRIK',...
           'icc_area_under_the_curve_patients_computed_with_matlab+orig.BRIK',...
           'icc_onset_delay_all_sample_computed_with_matlab+orig.BRIK',...
           'icc_onset_delay_patients_computed_with_matlab+orig.BRIK',...
           'icc_rise_decay_rate_all_sample_computed_with_matlab+orig.BRIK',...
           'icc_rise_decay_rate_patients_computed_with_matlab+orig.BRIK',...
           'icc_height_all_sample_computed_with_matlab+orig.BRIK',...
           'icc_height_patients_computed_with_matlab+orig.BRIK'};
       
Thresholds={0.40,... % fair
            0.60,... % good
            0.7,...  % Greg
            0.75};   % excellent
        
fprintf('\n\n\nData rescaled:\n')
        for ROI=1:numel(ROIs)
            fprintf('\n\nIn ROI: %s\n',ROIs{ROI})
            [mask]=BrikLoad(ROIs{ROI});
            mask(find(mask))=1;
            for ICC_map=1:numel(ICCs_maps)
                fprintf('\nIn ICC map: %s\n',ICCs_maps{ICC_map})
                ICC=BrikLoad(ICCs_maps{ICC_map});
                values_ICC_in_ROI=ICC.*mask;
                fprintf('\nMean value of ICCs: %.2f\n',mean(ICC(find(mask))))
                fprintf('\nStandard deviation value of ICCs: %.2f\n',std(ICC(find(mask))))
                fprintf('\nMedian value of ICCs: %.2f\n',median(ICC(find(mask))))
                for threshold=1:numel(Thresholds)
                    fprintf('%d voxels reliable over %d at threshlold %.2f\n',numel(find(values_ICC_in_ROI>Thresholds{threshold})),...
                        numel(find(mask)),...
                        Thresholds{threshold});
                end
            end
        end
% 
% % fprintf('\n\n\nData without outliers:\n')        
% % ICCs_maps={'icc_canonical_amplitude_all_sample_computed_with_matlab_wo+orig.BRIK',...
% %            'icc_canonical_amplitude_patients_computed_with_matlab_wo+orig.BRIK',...
% %            'icc_amplitude_all_sample_computed_with_matlab_wo+orig.BRIK',...
% %            'icc_amplitude_patients_computed_with_matlab_wo+orig.BRIK',...
% %            'icc_area_under_the_curve_all_sample_computed_with_matlab_wo+orig.BRIK',...
% %            'icc_area_under_the_curve_patients_computed_with_matlab_wo+orig.BRIK',...
% %            'icc_onset_delay_all_sample_computed_with_matlab_wo+orig.BRIK',...
% %            'icc_onset_delay_patients_computed_with_matlab_wo+orig.BRIK',...
% %            'icc_rise_decay_rate_all_sample_computed_with_matlab_wo+orig.BRIK',...
% %            'icc_rise_decay_rate_patients_computed_with_matlab_wo+orig.BRIK',...
% %            'icc_height_all_sample_computed_with_matlab_wo+orig.BRIK',...
% %            'icc_height_patients_computed_with_matlab_wo+orig.BRIK'};
% % 
% %            for ROI=1:numel(ROIs)
% %                fprintf('\n\nIn ROI: %s\n',ROIs{ROI})
% %                for ICC_map=1:numel(ICCs_maps)
% %                    fprintf('\nIn ICC map: %s\n',ICCs_maps{ICC_map})
% %                    for threshold=1:numel(Thresholds)
% %                        [mask]=BrikLoad(ROIs{ROI});
% %                        mask(find(mask))=1;
% %                        ICC=BrikLoad(ICCs_maps{ICC_map});
% %                        values_ICC_in_ROI=ICC.*mask;
% %                        fprintf('%d voxels reliable over %d at threshlold %.2f\n',numel(find(values_ICC_in_ROI>Thresholds{threshold})),...
% %                            numel(find(mask)),...
% %                            Thresholds{threshold});
% %                    end
% %                end
% %            end
%            
% % fprintf('\n\n\nCorrelations:\n')        
% % ICCs_maps={'corr_amplitude_all_sample.mat',...
% %             'corr_amplitude_patients.mat',...
% %             'corr_area_under_the_curve_all_sample.mat',...
% %             'corr_area_under_the_curve_patients.mat',...
% %             'corr_canonical_amplitude_all_sample.mat',...
% %             'corr_canonical_amplitude_patients.mat',...
% %             'corr_height_all_sample.mat',...
% %             'corr_height_patients.mat',...
% %             'corr_onset_delay_all_sample.mat',...
% %             'corr_onset_delay_patients.mat',...
% %             'corr_rise_decay_rate_all_sample.mat',...
% %             'corr_rise_decay_rate_patients.mat'};
% % 
% %            for ROI=1:numel(ROIs)
% %                fprintf('\n\nIn ROI: %s\n',ROIs{ROI})
% %                for ICC_map=1:numel(ICCs_maps)
% %                    fprintf('\nIn ICC map: %s\n',ICCs_maps{ICC_map})
% %                    for threshold=1:numel(Thresholds)
% %                        [mask]=BrikLoad(ROIs{ROI});
% %                        mask(find(mask))=1;
% %                        ICC=load(ICCs_maps{ICC_map});
% %                        values_ICC_in_ROI=ICC.corr.r.*mask;
% %                        fprintf('%d voxels reliable over %d at threshlold %.2f\n',numel(find(values_ICC_in_ROI>Thresholds{threshold})),...
% %                            numel(find(mask)),...
% %                            Thresholds{threshold});
% %                    end
% %                end
% %            end  
% 
% ICCs_maps={'corr_canonical_amplitude_all_sample_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_canonical_amplitude_patients_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_amplitude_all_sample_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_amplitude_patients_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_area_under_the_curve_all_sample_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_area_under_the_curve_patients_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_onset_delay_all_sample_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_onset_delay_patients_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_rise_decay_rate_all_sample_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_rise_decay_rate_patients_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_height_all_sample_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_height_patients_computed_with_matlab_with_covariates+orig.BRIK'};
%        
% Thresholds={0.40,... % fair
%             0.60,... % good
%             0.7,...  % Greg
%             0.75};   % excellent
%         
% fprintf('\n\n\nStandardized betas with covariates:\n')
%         for ROI=1:numel(ROIs)
%             fprintf('\n\nIn ROI: %s\n',ROIs{ROI})
%             for ICC_map=1:numel(ICCs_maps)
%                 fprintf('\nIn ICC map: %s\n',ICCs_maps{ICC_map})
%                 for threshold=1:numel(Thresholds)
%                     [mask]=BrikLoad(ROIs{ROI});
%                     mask(find(mask))=1;
%                     ICC=BrikLoad(ICCs_maps{ICC_map});
%                     values_ICC_in_ROI=ICC.*mask;
%                     fprintf('%d voxels reliable over %d at threshlold %.2f\n',numel(find(values_ICC_in_ROI>Thresholds{threshold})),...
%                         numel(find(mask)),...
%                         Thresholds{threshold});
%                 end
%             end
%         end

% ICCs_maps={'corr_p_value_canonical_amplitude_all_sample_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_p_value_canonical_amplitude_patients_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_p_value_amplitude_all_sample_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_p_value_amplitude_patients_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_p_value_area_under_the_curve_all_sample_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_p_value_area_under_the_curve_patients_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_p_value_onset_delay_all_sample_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_p_value_onset_delay_patients_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_p_value_rise_decay_rate_all_sample_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_p_value_rise_decay_rate_patients_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_p_value_height_all_sample_computed_with_matlab_with_covariates+orig.BRIK',...
%            'corr_p_value_height_patients_computed_with_matlab_with_covariates+orig.BRIK'};
%         
%         Thresholds={0.05};   % significant
%         
% fprintf('\n\n\nP values with covariates:\n')
%         for ROI=1:numel(ROIs)
%             fprintf('\n\nIn ROI: %s\n',ROIs{ROI})
%             for ICC_map=1:numel(ICCs_maps)
%                 fprintf('\nIn ICC map: %s\n',ICCs_maps{ICC_map})
%                 for threshold=1:numel(Thresholds)
%                     [mask]=BrikLoad(ROIs{ROI});
%                     mask(find(mask))=1;
%                     ICC=BrikLoad(ICCs_maps{ICC_map});
%                     values_ICC_in_ROI=ICC.*mask;
%                     fprintf('%d voxels reliable over %d at threshlold %.2f\n',numel(find(values_ICC_in_ROI(values_ICC_in_ROI~=0)<Thresholds{threshold})),...
%                         numel(find(mask)),...
%                         Thresholds{threshold});
%                 end
%             end
%         end

% ICCs_maps={'s_p_corr_without_covariates_canonical_amplitude_all_sample_computed_with_matlab+orig.BRIK',...
%            's_p_corr_without_covariates_canonical_amplitude_patients_computed_with_matlab+orig.BRIK',...
%            's_p_corr_without_covariates_amplitude_all_sample_computed_with_matlab+orig.BRIK',...
%            's_p_corr_without_covariates_amplitude_patients_computed_with_matlab+orig.BRIK',...
%            's_p_corr_without_covariates_area_under_the_curve_all_sample_computed_with_matlab+orig.BRIK',...
%            's_p_corr_without_covariates_area_under_the_curve_patients_computed_with_matlab+orig.BRIK',...
%            's_p_corr_without_covariates_onset_delay_all_sample_computed_with_matlab+orig.BRIK',...
%            's_p_corr_without_covariates_onset_delay_patients_computed_with_matlab+orig.BRIK',...
%            's_p_corr_without_covariates_rise_decay_rate_all_sample_computed_with_matlab+orig.BRIK',...
%            's_p_corr_without_covariates_rise_decay_rate_patients_computed_with_matlab+orig.BRIK',...
%            's_p_corr_without_covariates_height_all_sample_computed_with_matlab+orig.BRIK',...
%            's_p_corr_without_covariates_height_patients_computed_with_matlab+orig.BRIK'};
%        
% Thresholds={0.40,... % fair
%             0.60,... % good
%             0.7,...  % Greg
%             0.75};   % excellent
%         
% fprintf('\n\n\n Correlations without covariates:\n')
%         for ROI=1:numel(ROIs)
%             fprintf('\n\nIn ROI: %s\n',ROIs{ROI})
%             for ICC_map=1:numel(ICCs_maps)
%                 fprintf('\nIn ICC map: %s\n',ICCs_maps{ICC_map})
%                 for threshold=1:numel(Thresholds)
%                     [mask]=BrikLoad(ROIs{ROI});
%                     mask(find(mask))=1;
%                     ICC=BrikLoad(ICCs_maps{ICC_map});
%                     values_ICC_in_ROI=ICC.*mask;
%                     fprintf('%d voxels reliable over %d at threshlold %.2f\n',numel(find(values_ICC_in_ROI>Thresholds{threshold})),...
%                         numel(find(mask)),...
%                         Thresholds{threshold});
%                 end
%             end
%         end
%         
% ICCs_maps={'s_p_corr_with_covariates_canonical_amplitude_all_sample_computed_with_matlab+orig.BRIK',...
%            's_p_corr_with_covariates_canonical_amplitude_patients_computed_with_matlab+orig.BRIK',...
%            's_p_corr_with_covariates_amplitude_all_sample_computed_with_matlab+orig.BRIK',...
%            's_p_corr_with_covariates_amplitude_patients_computed_with_matlab+orig.BRIK',...
%            's_p_corr_with_covariates_area_under_the_curve_all_sample_computed_with_matlab+orig.BRIK',...
%            's_p_corr_with_covariates_area_under_the_curve_patients_computed_with_matlab+orig.BRIK',...
%            's_p_corr_with_covariates_onset_delay_all_sample_computed_with_matlab+orig.BRIK',...
%            's_p_corr_with_covariates_onset_delay_patients_computed_with_matlab+orig.BRIK',...
%            's_p_corr_with_covariates_rise_decay_rate_all_sample_computed_with_matlab+orig.BRIK',...
%            's_p_corr_with_covariates_rise_decay_rate_patients_computed_with_matlab+orig.BRIK',...
%            's_p_corr_with_covariates_height_all_sample_computed_with_matlab+orig.BRIK',...
%            's_p_corr_with_covariates_height_patients_computed_with_matlab+orig.BRIK'};
%        
% Thresholds={0.40,... % fair
%             0.60,... % good
%             0.7,...  % Greg
%             0.75};   % excellent
%         
% fprintf('\n\n\n Correlations with covariates:\n')
%         for ROI=1:numel(ROIs)
%             fprintf('\n\nIn ROI: %s\n',ROIs{ROI})
%             for ICC_map=1:numel(ICCs_maps)
%                 fprintf('\nIn ICC map: %s\n',ICCs_maps{ICC_map})
%                 for threshold=1:numel(Thresholds)
%                     [mask]=BrikLoad(ROIs{ROI});
%                     mask(find(mask))=1;
%                     ICC=BrikLoad(ICCs_maps{ICC_map});
%                     values_ICC_in_ROI=ICC.*mask;
%                     fprintf('%d voxels reliable over %d at threshlold %.2f\n',numel(find(values_ICC_in_ROI>Thresholds{threshold})),...
%                         numel(find(mask)),...
%                         Thresholds{threshold});
%                 end
%             end
%         end