function rl_nf_choose_your_reliability_threshold_cluster_corrected_a()
% rl_choose_your_reliability_threshold
% reads  .BRIK and .HEAD maps computed by
% rl_write_ICC_maps_computed_with_matlab and counts how many voxels
% are reliable in each ROI at different thresholds and display this
% information in the command window
% assumes there are ROIs of interest rendered in the space of the
% functionals

addpath ('/data/Siegle/matlab/afni_matlab');

ROIs={'Lamygdala'};

ICCs_maps={'icc_amplitude_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
    'icc_amplitude_active_data_standard_computed_with_matlab+tlrc.BRIK',...
    'icc_amplitude_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
    'icc_amplitude_control_data_standard_computed_with_matlab+tlrc.BRIK',...
    'icc_area_under_the_curve_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
    'icc_area_under_the_curve_active_data_standard_computed_with_matlab+tlrc.BRIK',...
    'icc_area_under_the_curve_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
    'icc_area_under_the_curve_control_data_standard_computed_with_matlab+tlrc.BRIK',...
    'icc_canonical_amplitude_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
    'icc_canonical_amplitude_active_data_standard_computed_with_matlab+tlrc.BRIK',...
    'icc_canonical_amplitude_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
    'icc_canonical_amplitude_control_data_standard_computed_with_matlab+tlrc.BRIK',...
    'icc_height_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
    'icc_height_active_data_standard_computed_with_matlab+tlrc.BRIK',...
    'icc_height_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
    'icc_height_control_data_standard_computed_with_matlab+tlrc.BRIK',...
    'icc_onset_delay_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
    'icc_onset_delay_active_data_standard_computed_with_matlab+tlrc.BRIK',...
    'icc_onset_delay_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
    'icc_onset_delay_control_data_standard_computed_with_matlab+tlrc.BRIK',...
    'icc_rise_decay_rate_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
    'icc_rise_decay_rate_active_data_standard_computed_with_matlab+tlrc.BRIK',...
    'icc_rise_decay_rate_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
    'icc_rise_decay_rate_control_data_standard_computed_with_matlab+tlrc.BRIK'};

Thresholds={0.40,... % fair
    0.60,... % good
    0.7,...  % Greg
    0.75};   % excellent

fprintf('\n\n\nData rescaled:\n')
for ICC_map=1:numel(ICCs_maps)
    fprintf('\n\nIn ICC map: %s\n',ICCs_maps{ICC_map})
    ICC=BrikLoad(ICCs_maps{ICC_map});
    for ROI=1:numel(ROIs)
        fprintf('\nIn ROI: %s\n',ROIs{ROI})
        fin=regexp(ICCs_maps{ICC_map},'icc_','split');
        if regexp(ICCs_maps{ICC_map},'_active_')
            meas=regexp(fin{2},'_active_','split');
            group='active';
        else
            meas=regexp(fin{2},'_control_','split');
            group='control';
        end
        preprocessing=regexp(meas{2},'_computed_with_matlab','split');
        % here
        for threshold=1:numel(Thresholds)
            if exist(sprintf('cluster_correction_adjusted/%.2f/masks_cluster_correction_by_map_and_ROI/%s/%s/%s/cluster_correction_mask+tlrc.BRIK',Thresholds{threshold},meas{1},group, preprocessing{1}(6:end)))
                [mask]=BrikLoad(sprintf('cluster_correction_adjusted/%.2f/masks_cluster_correction_by_map_and_ROI/%s/%s/%s/cluster_correction_mask+tlrc.BRIK',Thresholds{threshold},meas{1},group, preprocessing{1}(6:end)));
                mask(find(mask))=1;
                values_ICC_in_ROI=ICC.*mask;
                fprintf('%d voxels reliable over %d at threshlold %.2f\n',numel(find(values_ICC_in_ROI>Thresholds{threshold})),...
                    numel(find(mask)),...
                    Thresholds{threshold});
            else
                fprintf('no voxels reliable over %.2f\n', Thresholds{threshold});
            end
        end
    end
end
% 
% 
% ICCs_maps={'corr_amplitude_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_amplitude_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_amplitude_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_amplitude_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_area_under_the_curve_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_area_under_the_curve_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_area_under_the_curve_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_area_under_the_curve_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_canonical_amplitude_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_canonical_amplitude_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_canonical_amplitude_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_canonical_amplitude_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_height_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_height_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_height_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_height_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_onset_delay_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_onset_delay_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_onset_delay_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_onset_delay_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_rise_decay_rate_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_rise_decay_rate_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_rise_decay_rate_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_rise_decay_rate_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK'};
%        
% Thresholds={0.40,... % fair
%             0.60,... % good
%             0.7,...  % Greg
%             0.75};   % excellent
%         
% fprintf('\n\n\nStandardized betas with covariates:\n')
%         for ROI=1:numel(ROIs)
%             fprintf('\n\nIn ROI: %s\n',ROIs{ROI})
%             for ICC_map=1:numel(ICCs_maps)
%                 fprintf('\nIn ICC map: %s\n',ICCs_maps{ICC_map})
%                 for threshold=1:numel(Thresholds)
%                     [mask]=BrikLoad(ROIs{ROI});
%                     mask(find(mask))=1;
%                     ICC=BrikLoad(ICCs_maps{ICC_map});
%                     values_ICC_in_ROI=ICC.*mask;
%                     fprintf('%d voxels reliable over %d at threshlold %.2f\n',numel(find(values_ICC_in_ROI>Thresholds{threshold})),...
%                         numel(find(mask)),...
%                         Thresholds{threshold});
%                 end
%             end
%         end
        
        
% % ICCs_maps={'r_amplitude_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_amplitude_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_amplitude_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_amplitude_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_area_under_the_curve_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_area_under_the_curve_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_area_under_the_curve_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_area_under_the_curve_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_canonical_amplitude_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_canonical_amplitude_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_canonical_amplitude_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_canonical_amplitude_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_height_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_height_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_height_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_height_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_onset_delay_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_onset_delay_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_onset_delay_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_onset_delay_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_rise_decay_rate_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_rise_decay_rate_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_rise_decay_rate_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
% %            'r_rise_decay_rate_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK'};
% %        
% % Thresholds={0.40,... % fair
% %             0.60,... % good
% %             0.7,...  % Greg
% %             0.75};   % excellent
% %         
% % fprintf('\n\n\n Correlations with covariates:\n')
% %         for ROI=1:numel(ROIs)
% %             fprintf('\n\nIn ROI: %s\n',ROIs{ROI})
% %             for ICC_map=1:numel(ICCs_maps)
% %                 fprintf('\nIn ICC map: %s\n',ICCs_maps{ICC_map})
% %                 for threshold=1:numel(Thresholds)
% %                     [mask]=BrikLoad(ROIs{ROI});
% %                     mask(find(mask))=1;
% %                     ICC=BrikLoad(ICCs_maps{ICC_map});
% %                     values_ICC_in_ROI=ICC.*mask;
% %                     fprintf('%d voxels reliable over %d at threshlold %.2f\n',numel(find(values_ICC_in_ROI>Thresholds{threshold})),...
% %                         numel(find(mask)),...
% %                         Thresholds{threshold});
% %                 end
% %             end
% %         end

% ICCs_maps={'corr_p_value_amplitude_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_amplitude_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_amplitude_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_amplitude_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_area_under_the_curve_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_area_under_the_curve_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_area_under_the_curve_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_area_under_the_curve_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_canonical_amplitude_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_canonical_amplitude_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_canonical_amplitude_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_canonical_amplitude_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_height_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_height_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_height_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_height_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_onset_delay_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_onset_delay_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_onset_delay_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_onset_delay_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_rise_decay_rate_active_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_rise_decay_rate_active_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_rise_decay_rate_control_data_BV_style_computed_with_matlab_with_covariates+tlrc.BRIK',...
%            'corr_p_value_rise_decay_rate_control_data_standard_computed_with_matlab_with_covariates+tlrc.BRIK'};
%        
% Thresholds={0.05};   % significant
%         
% fprintf('\n\n\n Correlations with covariates:\n')
%         for ROI=1:numel(ROIs)
%             fprintf('\n\nIn ROI: %s\n',ROIs{ROI})
%             for ICC_map=1:numel(ICCs_maps)
%                 fprintf('\nIn ICC map: %s\n',ICCs_maps{ICC_map})
%                 for threshold=1:numel(Thresholds)
%                     [mask]=BrikLoad(ROIs{ROI});
%                     mask(find(mask))=1;
%                     ICC=BrikLoad(ICCs_maps{ICC_map});
%                     values_ICC_in_ROI=ICC.*mask;
%                     fprintf('%d voxels reliable over %d at threshlold %.2f\n',numel(find(values_ICC_in_ROI(values_ICC_in_ROI~=0)<Thresholds{threshold})),...
%                         numel(find(mask)),...
%                         Thresholds{threshold});
%                 end
%             end
%         end

% ICCs_maps={'s_p_corr_without_covariates_amplitude_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_amplitude_active_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_amplitude_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_amplitude_control_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_area_under_the_curve_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_area_under_the_curve_active_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_area_under_the_curve_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_area_under_the_curve_control_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_canonical_amplitude_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_canonical_amplitude_active_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_canonical_amplitude_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_canonical_amplitude_control_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_height_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_height_active_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_height_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_height_control_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_onset_delay_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_onset_delay_active_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_onset_delay_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_onset_delay_control_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_rise_decay_rate_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_rise_decay_rate_active_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_rise_decay_rate_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_without_covariates_rise_decay_rate_control_data_standard_computed_with_matlab+tlrc.BRIK'};
%        
% Thresholds={0.40,... % fair
%             0.60,... % good
%             0.7,...  % Greg
%             0.75};   % excellent
%         
% fprintf('\n\n\n Correlations without covariates:\n')
%         for ROI=1:numel(ROIs)
%             fprintf('\n\nIn ROI: %s\n',ROIs{ROI})
%             for ICC_map=1:numel(ICCs_maps)
%                 fprintf('\nIn ICC map: %s\n',ICCs_maps{ICC_map})
%                 for threshold=1:numel(Thresholds)
%                     [mask]=BrikLoad(ROIs{ROI});
%                     mask(find(mask))=1;
%                     ICC=BrikLoad(ICCs_maps{ICC_map});
%                     values_ICC_in_ROI=ICC.*mask;
%                     fprintf('%d voxels reliable over %d at threshlold %.2f\n',numel(find(values_ICC_in_ROI>Thresholds{threshold})),...
%                         numel(find(mask)),...
%                         Thresholds{threshold});
%                 end
%             end
%         end
%         
% ICCs_maps={'s_p_corr_with_covariates_amplitude_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_amplitude_active_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_amplitude_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_amplitude_control_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_area_under_the_curve_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_area_under_the_curve_active_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_area_under_the_curve_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_area_under_the_curve_control_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_canonical_amplitude_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_canonical_amplitude_active_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_canonical_amplitude_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_canonical_amplitude_control_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_height_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_height_active_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_height_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_height_control_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_onset_delay_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_onset_delay_active_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_onset_delay_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_onset_delay_control_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_rise_decay_rate_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_rise_decay_rate_active_data_standard_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_rise_decay_rate_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
%            's_p_corr_with_covariates_rise_decay_rate_control_data_standard_computed_with_matlab+tlrc.BRIK'};
%        
% Thresholds={0.40,... % fair
%             0.60,... % good
%             0.7,...  % Greg
%             0.75};   % excellent
%         
% fprintf('\n\n\n Correlations with covariates:\n')
%         for ROI=1:numel(ROIs)
%             fprintf('\n\nIn ROI: %s\n',ROIs{ROI})
%             for ICC_map=1:numel(ICCs_maps)
%                 fprintf('\nIn ICC map: %s\n',ICCs_maps{ICC_map})
%                 for threshold=1:numel(Thresholds)
%                     [mask]=BrikLoad(ROIs{ROI});
%                     mask(find(mask))=1;
%                     ICC=BrikLoad(ICCs_maps{ICC_map});
%                     values_ICC_in_ROI=ICC.*mask;
%                     fprintf('%d voxels reliable over %d at threshlold %.2f\n',numel(find(values_ICC_in_ROI>Thresholds{threshold})),...
%                         numel(find(mask)),...
%                         Thresholds{threshold});
%                 end
%             end
%         end