function rl_nf_which_model_best()
% Compare semi partial correlations with and without covariates across
% different first models
% This code has been described in Compere et al. (2020)

addpath('/data/Siegle/matlab/afni_matlab');
ROIs={'Lamygdala_resampled+tlrc.BRIK'};
ROI_name={'Amygdala'};
   
sr_maps_control_data={'s_p_corr_without_covariates_canonical_amplitude_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_without_covariates_canonical_amplitude_control_data_standard_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_with_covariates_canonical_amplitude_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_with_covariates_canonical_amplitude_control_data_standard_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_without_covariates_amplitude_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_without_covariates_amplitude_control_data_standard_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_with_covariates_amplitude_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_with_covariates_amplitude_control_data_standard_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_without_covariates_area_under_the_curve_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_without_covariates_area_under_the_curve_control_data_standard_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_with_covariates_area_under_the_curve_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_with_covariates_area_under_the_curve_control_data_standard_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_without_covariates_onset_delay_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_without_covariates_onset_delay_control_data_standard_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_with_covariates_onset_delay_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_with_covariates_onset_delay_control_data_standard_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_without_covariates_rise_decay_rate_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_without_covariates_rise_decay_rate_control_data_standard_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_with_covariates_rise_decay_rate_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_with_covariates_rise_decay_rate_control_data_standard_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_without_covariates_height_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_without_covariates_height_control_data_standard_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_with_covariates_height_control_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                      's_p_corr_with_covariates_height_control_data_standard_computed_with_matlab+tlrc.BRIK'};


sr_maps_active_data={'s_p_corr_without_covariates_canonical_amplitude_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_without_covariates_canonical_amplitude_active_data_standard_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_with_covariates_canonical_amplitude_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_with_covariates_canonical_amplitude_active_data_standard_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_without_covariates_amplitude_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_without_covariates_amplitude_active_data_standard_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_with_covariates_amplitude_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_with_covariates_amplitude_active_data_standard_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_without_covariates_area_under_the_curve_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_without_covariates_area_under_the_curve_active_data_standard_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_with_covariates_area_under_the_curve_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_with_covariates_area_under_the_curve_active_data_standard_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_without_covariates_onset_delay_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_without_covariates_onset_delay_active_data_standard_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_with_covariates_onset_delay_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_with_covariates_onset_delay_active_data_standard_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_without_covariates_rise_decay_rate_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_without_covariates_rise_decay_rate_active_data_standard_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_with_covariates_rise_decay_rate_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_with_covariates_rise_decay_rate_active_data_standard_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_without_covariates_height_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_without_covariates_height_active_data_standard_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_with_covariates_height_active_data_BV_style_computed_with_matlab+tlrc.BRIK',...
                     's_p_corr_with_covariates_height_active_data_standard_computed_with_matlab+tlrc.BRIK'};

sr_name={'Canonical amplitude without covariates BV style',...
         'Canonical amplitude without covariates standard',...
         'Canonical amplitude with covariates BV style',...
         'Canonical amplitude with covariates standard',...
         'Amplitude without covariates BV style',...
         'Amplitude without covariates standard',...
         'Amplitude with covariates BV style',...
         'Amplitude with covariates standard',...
         'Area under the curve without covariates BV style',...
         'Area under the curve without covariates standard',...
         'Area under the curve with covariates BV style',...
         'Area under the curve with covariates standard',...
         'Onset delay without covariates BV style',...
         'Onset delay without covariates standard',...
         'Onset delay with covariates BV style',...
         'Onset delay with covariates standard',...
         'Rise decay without covariates BV style',...
         'Rise decay without covariates standard',...
         'Rise decay with covariates BV style',...
         'Rise decay with covariates standard',...
         'Height without covariates BV style',...
         'Height without covariates standard',...
         'Height with covariates BV style',...
         'Height with covariates standard'};

     % On controls data
for ROI=1:numel(ROIs)
    [mask]=BrikLoad(ROIs{ROI});
    mask(find(mask))=1;
    values_sr_in_ROI_all_models_control_data=zeros(numel(find(mask)),numel(sr_maps_control_data));
    for sr_map=1:numel(sr_maps_control_data)
        sr=BrikLoad(sr_maps_control_data{sr_map});
        values_sr_in_ROI=sr.*mask;
        values_sr_in_ROI_all_models_control_data(:,sr_map)=values_sr_in_ROI(find(mask));
        if any(~isnan(values_sr_in_ROI(find(mask))))
            non_normal_distribution_in_ROI_all_models_control_data(sr_map)=kstest(values_sr_in_ROI(find(mask))); % result h is 1 if the test rejects the null hypothesis that the data come from a standard normal distribution, 0 otherwise
        else
            non_normal_distribution_in_ROI_all_models_control_data(sr_map)=1;
        end
    end
    % Plot distribution of reliability estimates
    figure(ROI); 
    multihistimg(values_sr_in_ROI_all_models_control_data,100,sr_name,1);
    title(sprintf('Control data: %s',ROI_name{ROI}));
    % Test if distributions are different with non parametric test
   if any(find(non_normal_distribution_in_ROI_all_models_control_data==1)) && ~any(find(non_normal_distribution_in_ROI_all_models_control_data==0)) 
       [p,tbl,stat]=kruskalwallis(values_sr_in_ROI_all_models_control_data,sr_name,'off');
       hold on;
       xlabel(sprintf('Kruskal-Wallis: p=%1.3f',p));
       hold off
       % If they are, we do a non parametric post hoc comparison
       if p<0.05
           figure(ROI+1);
           [c,m]=multcompare(stat);  
       end
   elseif any(find(non_normal_distribution_in_ROI_all_models_control_data==0)) && ~any(find(non_normal_distribution_in_ROI_all_models_control_data==1))
       fprintf('One-wayANOVA')
   else
       fprintf('mixed distribution\n')
   end
end


% Does exactly the same on data from the experimental group
for ROI=1:numel(ROIs)
    [mask]=BrikLoad(ROIs{ROI});
    mask(find(mask))=1;
    values_sr_in_ROI_all_models_active_data=zeros(numel(find(mask)),numel(sr_maps_active_data));
    for sr_map=1:numel(sr_maps_active_data)
        sr=BrikLoad(sr_maps_active_data{sr_map});
        values_sr_in_ROI=sr.*mask;
        values_sr_in_ROI_all_models_active_data(:,sr_map)=values_sr_in_ROI(find(mask));
        if any(~isnan(values_sr_in_ROI(find(mask))))
            non_normal_distribution_in_ROI_all_models_active_data(sr_map)=kstest(values_sr_in_ROI(find(mask))); % result h is 1 if the test rejects the null hypothesis that the data come from a standard normal distribution, 0 otherwise
        else
            non_normal_distribution_in_ROI_all_models_active_data(sr_map)=1;
        end
    end
    % Plot
    figure(ROI+5);
    multihistimg(values_sr_in_ROI_all_models_active_data,100,sr_name,1);   
    title(sprintf('Active data: %s',ROI_name{ROI}));
   % Test
   if any(find(non_normal_distribution_in_ROI_all_models_active_data==1)) && ~any(find(non_normal_distribution_in_ROI_all_models_active_data==0)) 
       [p,tbl,stat]=kruskalwallis(values_sr_in_ROI_all_models_active_data,sr_name,'off');
       hold on;
       xlabel(sprintf('Kruskal-Wallis: p=%1.3f',p));
       hold off
       if p<0.05
           figure(ROI+6)
           [c,m]=multcompare(stat);
       end    
   elseif any(find(non_normal_distribution_in_ROI_all_models_active_data==0)) && ~any(find(non_normal_distribution_in_ROI_all_models_active_data==1))
       fprintf('One-wayANOVA')
   else
       fprintf('mixed distribution\n')
   end
end